/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Terminkalender;

/**
 *
 * @author Richard Hofmeister
 */
public class AppointmentGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentGUI
     */
    
    AppointmentModell apm = new AppointmentModell();
    
    public AppointmentGUI() {
        initComponents();
        jList1.setModel(apm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        btUebernehmen = new javax.swing.JButton();
        btAbbrechen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jMenuItem1.setText("hinzufügen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdd(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("löschen");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDelete(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("ändern");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onChange(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jDialog1.setTitle("Termin-Eingabe");
        jDialog1.getContentPane().setLayout(new java.awt.GridLayout(7, 2));

        jLabel3.setText("Tag:");
        jDialog1.getContentPane().add(jLabel3);

        tfTag.setText("8");
        jDialog1.getContentPane().add(tfTag);

        jLabel1.setText("Monat:");
        jDialog1.getContentPane().add(jLabel1);

        tfMonat.setText("9");
        jDialog1.getContentPane().add(tfMonat);

        jLabel2.setText("Jahr:");
        jDialog1.getContentPane().add(jLabel2);

        tfJahr.setText("2014");
        jDialog1.getContentPane().add(tfJahr);

        jLabel5.setText("Stunde");
        jDialog1.getContentPane().add(jLabel5);

        tfStunde.setText("8");
        jDialog1.getContentPane().add(tfStunde);

        jLabel6.setText("Minute:");
        jDialog1.getContentPane().add(jLabel6);

        tfMinute.setText("45");
        jDialog1.getContentPane().add(tfMinute);

        jLabel4.setText("Text:");
        jDialog1.getContentPane().add(jLabel4);

        tfText.setText("POS1-Workshop");
        jDialog1.getContentPane().add(tfText);

        btUebernehmen.setText("übernehmen");
        jDialog1.getContentPane().add(btUebernehmen);

        btAbbrechen.setText("abbrechen");
        jDialog1.getContentPane().add(btAbbrechen);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("termine");

        jList1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdd
        
    }//GEN-LAST:event_onAdd

    private void onDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDelete
        
    }//GEN-LAST:event_onDelete

    private void onChange(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onChange
        
    }//GEN-LAST:event_onChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btUebernehmen;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<Appointment> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
}
