/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Terminkalender;

import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Locale;

/**
 *
 * @author Richard Hofmeister
 */
public class AppointmentDlg extends javax.swing.JDialog {
    private Appointment apt;
    
    /**
     * Creates new form AppointmentDlg
     */
    
    private AppointmentModell apm = new AppointmentModell();
    
    
    
    public AppointmentDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        btUebernehmen = new javax.swing.JButton();
        btAbbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setText("Tag:");
        getContentPane().add(jLabel1);

        tfTag.setText("8");
        getContentPane().add(tfTag);

        jLabel2.setText("Monat:");
        getContentPane().add(jLabel2);

        tfMonat.setText("9");
        getContentPane().add(tfMonat);

        jLabel3.setText("Jahr:");
        getContentPane().add(jLabel3);

        tfJahr.setText("2018");
        getContentPane().add(tfJahr);

        jLabel4.setText("Stunde:");
        getContentPane().add(jLabel4);

        tfStunde.setText("8");
        getContentPane().add(tfStunde);

        jLabel6.setText("Minute:");
        getContentPane().add(jLabel6);

        tfMinute.setText("45");
        getContentPane().add(tfMinute);

        jLabel5.setText("Text:");
        getContentPane().add(jLabel5);

        tfText.setText("POS1-Workshop");
        getContentPane().add(tfText);

        btUebernehmen.setText("übernehmen");
        btUebernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUebernehmen(evt);
            }
        });
        getContentPane().add(btUebernehmen);

        btAbbrechen.setText("abbrechen");
        btAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAbbrechen(evt);
            }
        });
        getContentPane().add(btAbbrechen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAbbrechen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAbbrechen
        this.dispose();
    }//GEN-LAST:event_onAbbrechen

    private void onUebernehmen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onUebernehmen
        int tag = Integer.parseInt(tfTag.getText());
        int monat = Integer.parseInt(tfMonat.getText());
        int jahr = Integer.parseInt(tfJahr.getText());
        int stunde = Integer.parseInt(tfStunde.getText());
        int minute = Integer.parseInt(tfMinute.getText());
        
        apt = new Appointment(LocalDateTime.of(jahr, monat, tag, stunde, minute), tfText.getText());
        this.dispose();
    }//GEN-LAST:event_onUebernehmen

    public Appointment getApt() {
        return apt;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentDlg dialog = new AppointmentDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btUebernehmen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
}
